config/routes.rb
TIServer::Application.routes.draw do
  resources :nfcobjectattributes

  resources :nfcobjects
  
   

end

app/models/nfcobject.rb
class Nfcobject < ActiveRecord::Base
  attr_accessible :description, :name, :nfctype
  has_many :nfcobjectattributes 
  
  def to_param
    self.name
  end
  
end

app/models/nfcobjectattribute.rb
class Nfcobjectattribute < ActiveRecord::Base
  attr_accessible :name, :nfcobject_id, :value
  belongs_to :nfcobject
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nfcobjectattributes_controller.rb
class NfcobjectattributesController < ApplicationController
  # GET /nfcobjectattributes
  # GET /nfcobjectattributes.json
  def index
    @nfcobjectattributes = Nfcobjectattribute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nfcobjectattributes }
    end
  end

  # GET /nfcobjectattributes/1
  # GET /nfcobjectattributes/1.json
  def show
    @nfcobjectattribute = Nfcobjectattribute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nfcobjectattribute, :except => [ :id, :created_at, :updated_at ] }
    end
  end

  # GET /nfcobjectattributes/new
  # GET /nfcobjectattributes/new.json
  def new
    @nfcobjectattribute = Nfcobjectattribute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nfcobjectattribute }
    end
  end

  # GET /nfcobjectattributes/1/edit
  def edit
    @nfcobjectattribute = Nfcobjectattribute.find(params[:id])
  end

  # POST /nfcobjectattributes
  # POST /nfcobjectattributes.json
  def create
    @nfcobjectattribute = Nfcobjectattribute.new(params[:nfcobjectattribute])

    respond_to do |format|
      if @nfcobjectattribute.save
        format.html { redirect_to @nfcobjectattribute, notice: 'Nfcobjectattribute was successfully created.' }
        format.json { render json: @nfcobjectattribute, status: :created, location: @nfcobjectattribute }
      else
        format.html { render action: "new" }
        format.json { render json: @nfcobjectattribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nfcobjectattributes/1
  # PUT /nfcobjectattributes/1.json
  def update
    @nfcobjectattribute = Nfcobjectattribute.find(params[:id])

    respond_to do |format|
      if @nfcobjectattribute.update_attributes(params[:nfcobjectattribute])
        format.html { redirect_to @nfcobjectattribute, notice: 'Nfcobjectattribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nfcobjectattribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nfcobjectattributes/1
  # DELETE /nfcobjectattributes/1.json
  def destroy
    @nfcobjectattribute = Nfcobjectattribute.find(params[:id])
    @nfcobjectattribute.destroy

    respond_to do |format|
      format.html { redirect_to nfcobjectattributes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/nfcobjects_controller.rb
class NfcobjectsController < ApplicationController
  # GET /nfcobjects
  # GET /nfcobjects.json
  def index
    @nfcobjects = Nfcobject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nfcobjects }
    end
  end

  # GET /nfcobjects/1
  # GET /nfcobjects/1.json
  def show
    @nfcobject = Nfcobject.find_by_name(params[:id])
	@attributes = @nfcobject.nfcobjectattributes
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nfcobject, :except => [ :id, :created_at, :updated_at ], :include => { :nfcobjectattributes => { :except => [ :id, :created_at, :updated_at ] }}}
    end
  end

  # GET /nfcobjects/new
  # GET /nfcobjects/new.json
  def new
    @nfcobject = Nfcobject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nfcobject }
    end
  end

  # GET /nfcobjects/1/edit
  def edit
    @nfcobject = Nfcobject.find(params[:id])
  end

  # POST /nfcobjects
  # POST /nfcobjects.json
  def create
    @nfcobject = Nfcobject.new(params[:nfcobject])

    respond_to do |format|
      if @nfcobject.save
        format.html { redirect_to @nfcobject, notice: 'Nfcobject was successfully created.' }
        format.json { render json: @nfcobject, status: :created, location: @nfcobject }
      else
        format.html { render action: "new" }
        format.json { render json: @nfcobject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nfcobjects/1
  # PUT /nfcobjects/1.json
  def update
    @nfcobject = Nfcobject.find(params[:id])

    respond_to do |format|
      if @nfcobject.update_attributes(params[:nfcobject])
        format.html { redirect_to @nfcobject, notice: 'Nfcobject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nfcobject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nfcobjects/1
  # DELETE /nfcobjects/1.json
  def destroy
    @nfcobject = Nfcobject.find(params[:id])
    @nfcobject.destroy

    respond_to do |format|
      format.html { redirect_to nfcobjects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nfcobjectattributes_helper.rb
module NfcobjectattributesHelper
end

app/helpers/nfcobjects_helper.rb
module NfcobjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TIServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nfcobjectattributes/_form.html.erb
<%= form_for(@nfcobjectattribute) do |f| %>
  <% if @nfcobjectattribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nfcobjectattribute.errors.count, "error") %> prohibited this nfcobjectattribute from being saved:</h2>

      <ul>
      <% @nfcobjectattribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :nfcobject_id %><br />
    <%= f.number_field :nfcobject_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nfcobjectattributes/edit.html.erb
<h1>Editing nfcobjectattribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @nfcobjectattribute %> |
<%= link_to 'Back', nfcobjectattributes_path %>

app/views/nfcobjectattributes/index.html.erb
<h1>Listing nfcobjectattributes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th>Nfcobject</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nfcobjectattributes.each do |nfcobjectattribute| %>
  <tr>
    <td><%= nfcobjectattribute.name %></td>
    <td><%= nfcobjectattribute.value %></td>
    <td><%= nfcobjectattribute.nfcobject_id %></td>
    <td><%= link_to 'Show', nfcobjectattribute %></td>
    <td><%= link_to 'Edit', edit_nfcobjectattribute_path(nfcobjectattribute) %></td>
    <td><%= link_to 'Destroy', nfcobjectattribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nfcobjectattribute', new_nfcobjectattribute_path %>

app/views/nfcobjectattributes/new.html.erb
<h1>New nfcobjectattribute</h1>

<%= render 'form' %>

<%= link_to 'Back', nfcobjectattributes_path %>

app/views/nfcobjectattributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @nfcobjectattribute.name %>
</p>

<p>
  <b>Value:</b>
  <%= @nfcobjectattribute.value %>
</p>

<p>
  <b>Nfcobject:</b>
  <%= @nfcobjectattribute.nfcobject_id %>
</p>


<%= link_to 'Edit', edit_nfcobjectattribute_path(@nfcobjectattribute) %> |
<%= link_to 'Back', nfcobjectattributes_path %>

app/views/nfcobjects/_form.html.erb
<%= form_for(@nfcobject) do |f| %>
  <% if @nfcobject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nfcobject.errors.count, "error") %> prohibited this nfcobject from being saved:</h2>

      <ul>
      <% @nfcobject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :nfctype %><br />
    <%= f.text_field :nfctype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nfcobjects/edit.html.erb
<h1>Editing nfcobject</h1>

<%= render 'form' %>

<%= link_to 'Show', @nfcobject %> |
<%= link_to 'Back', nfcobjects_path %>

app/views/nfcobjects/index.html.erb
<h1>Listing nfcobjects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Nfctype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nfcobjects.each do |nfcobject| %>
  <tr>
    <td><%= nfcobject.name %></td>
    <td><%= nfcobject.description %></td>
    <td><%= nfcobject.nfctype %></td>
    <td><%= link_to 'Show', nfcobject %></td>
    <td><%= link_to 'Edit', edit_nfcobject_path(nfcobject) %></td>
    <td><%= link_to 'Destroy', nfcobject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nfcobject', new_nfcobject_path %>

app/views/nfcobjects/new.html.erb
<h1>New nfcobject</h1>

<%= render 'form' %>

<%= link_to 'Back', nfcobjects_path %>

app/views/nfcobjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @nfcobject.name %>
</p>

<p>
  <b>Description:</b>
  <%= @nfcobject.description %>
</p>

<p>
  <b>Nfctype:</b>
  <%= @nfcobject.nfctype %>
</p>


<%= link_to 'Edit', edit_nfcobject_path(@nfcobject) %> |
<%= link_to 'Back', nfcobjects_path %>